version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: sgh-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: sgh-trasporti
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - sgh-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sgh-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:${MONGO_PASSWORD:-changeme}@mongodb:27017/sgh-trasporti?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRE: 7d
      JWT_REFRESH_EXPIRE: 30d
      EMAIL_HOST: smtp-mail.outlook.com
      EMAIL_PORT: 587
      EMAIL_USER: service.sgh.trasporti@hotmail.com
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: SGH Trasporti <service.sgh.trasporti@hotmail.com>
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      ADMIN_EMAIL: service.sgh.trasporti@hotmail.com
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MAX_FILE_SIZE: 5242880
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    ports:
      - "5000:5000"
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - sgh-network

  # Frontend Next.js App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sgh-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5000/api}
      NEXT_PUBLIC_APP_NAME: SGH Trasporti
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    ports:
      - "3000:3000"
    networks:
      - sgh-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  backend_uploads:
    driver: local

networks:
  sgh-network:
    driver: bridge
