services:
  - type: web
    name: sgh-trasporti-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: JWT_REFRESH_EXPIRE
        value: 30d
      - key: EMAIL_HOST
        value: smtp-mail.outlook.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: service.sgh.trasporti@hotmail.com
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        value: SGH Trasporti <service.sgh.trasporti@hotmail.com>
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_EMAIL
        value: service.sgh.trasporti@hotmail.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
